### ISSUE TITLE
Fiji/ImageJ initialization problem - Linux Pop_OS

### ISSUE THREAD

**Issue by jenna-tomkinson** [WayScience/IDR_stream#19]
I noticed an issue where since I use Fiji on a daily basis and update it, then it can not initialize it when using idrstream. I am unsure what causes Fiji to not be usable for idrstream, but it seems using the program and GUI causes issues.

When I get a clean version of Fiji (installed and not opened), idrstream is fine. But, I can not have two Fiji apps installed on my Linux machine or it starts to cause issues.

Essentially, a user would have to reinstall Fiji every time they use idrstream and then delete it if they already have Fiji installed.

**Comment by jenna-tomkinson** [comment]
As well, I am getting this error when using the cellprofiler notebook example where it will give me an error when initializing Fiji with this setup (which is the default from when it was previously run):

```python
fiji_path = pathlib.Path("~/Desktop/Fiji_for_idrstream/Fiji.app")
stream.init_preprocessor(fiji_path)
```
Giving me this error as output:
```
TypeError: expected string or bytes-like object
```

This is error is fixed if I change it to `/home/jenna/Desktop/Fiji_for_idrstream/Fiji.app`, but I am unsure why it doesn't run on my end like this when it worked on another machine.

**Comment by jenna-tomkinson** [comment]
After changing the pathing, I run into this new error that states:
```
TypeError: Class net.imglib2.python.Helpers is not found
```
This happened both after using the Fiji that I have been using daily and when I used an old download `.zip` file with a clean install of Fiji.

**Comment by jenna-tomkinson** [comment]
It now works once I download Fiji from a completely new .zip file, I will have to delete this and start all over since having two Fiji apps breaks and I can not do the things I need to.

**Comment by roshankern** [comment]
> As well, I am getting this error when using the cellprofiler notebook example where it will give me an error when initializing Fiji with this setup (which is the default from when it was previously run):
> 
> ```python
> fiji_path = pathlib.Path("~/Desktop/Fiji_for_idrstream/Fiji.app")
> stream.init_preprocessor(fiji_path)
> ```
> 
> Giving me this error as output:
> 
> ```
> TypeError: expected string or bytes-like object
> ```
> 
> This is error is fixed if I change it to `/home/jenna/Desktop/Fiji_for_idrstream/Fiji.app`, but I am unsure why it doesn't run on my end like this when it worked on another machine.

I made an error in setting the Fiji path with `~/`, it seems that `pathlib` is not able to use `~`. Sorry I didn't fix this earlier and it caused you issues. This will be addressed in the next PR.

**Comment by roshankern** [comment]
> It now works once I download Fiji from a completely new .zip file, I will have to delete this and start all over since having two Fiji apps breaks and I can not do the things I need to.

What does having two Fiji apps break? I currently have 3 separate Fiji folders on my computer (freshly unzipped) and I am able to use Fiji/IDR_stream without any issues.

**Comment by jenna-tomkinson** [comment]
> > It now works once I download Fiji from a completely new .zip file, I will have to delete this and start all over since having two Fiji apps breaks and I can not do the things I need to.
> 
> What does having two Fiji apps break? I currently have 3 separate Fiji folders on my computer (freshly unzipped) and I am able to use Fiji/IDR_stream without any issues.

Looks like it was a glitch. It was just a coincidence it happened right after I installed another clean version 🤷‍♀️.

I confirmed that the path in the notebook just wasn’t to the clean version of Fiji (e.g., ~/Desktop/Fiji.app). I did not realize I had the clean version in a test folder before installing again.

But, this issue confirms that the documentation in the README should be updated to reflect that Fiji has to be a clean install either somewhere on their machine or into the idrstream repo. I will make this into a PR soon.

Thank you for figuring out that issue with the path! Glad we could clear this up @roshankern!
